apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - name: "Umbrella IdM"
    mappingMethod: claim
    type: LDAP
    ldap:
      attributes:
        id:
        - dn
        email:
        - mail
        name:
        - cn
        preferredUsername:
        - uid
      bindDN: uid=ocp-service-account,cn=users,cn=accounts,dc=umbrella,dc=local
      bindPassword:
        name: oauth-ldap-bind-secret
      ca:
        name: oauth-ldap-ca-config-map
      insecure: false
      url: ldap://idm1.umbrella.local/cn=users,cn=accounts,dc=umbrella,dc=local?uid
